locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.index, name='index'),
        path('books/', views.BookListView.as_view(), name='books'),
        path('book/<int:pk>', views.BookDetailView.as_view(), name = 'book-detail'),
        path('authors/', views.AuthorListView.as_view(), name='authors'),
        path('author/<int:pk>', views.AuthorDetailView.as_view(), name = 'author-detail'),
        path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
        path('allbooks/', views.LoanedBooksListView.as_view(), name='all-borrowed'),
]

locallibrary/locallibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse # used in get_absolute_url() to get URL for specific ID
from django.db.models import UniqueConstraint # Constrains fields ot unique values
from django.db.models.functions import Lower # returns lower cased value of fields
from django.conf import settings
from datetime import date
import uuid # Required for book instances

# Create your models here.

class Genre(models.Model):
    """Model representing book genre"""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book genre (e.g. Science Ficition, French Poetry, etc.)"
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular genre instance."""
        return reverse('genre-detail', arg=[str(self.id)])

    class Meta:
        constraints = [
                UniqueConstraint(
                    Lower('name'),
                    name='genre_name_case_insensitive_unique',
                    violation_error_message='Genre already exists (case insensitive match)'
                ),
        ]

class Book(models.Model):
    """Model representing a Book (but not a specific copy of a book)"""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    # Foreign key is used because a book can only have one author, but authors can have multiple books
    # Author as a string rather than object vecause it hasn't been declared yet in file. 

    summary = models.TextField(
                max_length=1000,
                help_text="Enter a brief description of the book"
            )
    isbn = models.CharField(
                'ISBN', 
                max_length=13,
                unique=True,
                help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'
            )
    # ManyToManyField used because genre can contain many books. Books can cover many genres. 
    # Genre class has already been defined so we can specifcy from the object above.
    genre = models.ManyToManyField(
                Genre, 
                help_text="Select a genre for this book"
            )

    language = models.ForeignKey(
                'Language',
                on_delete=models.SET_NULL,
                null=True,
                help_text="Select a language for this book"
            )

    def display_genre(self):
        """ Creating a string for the genre. This is required to display the genre in admin because of ManyToManyField """
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    def __str__(self):
        """String for representing the Model object"""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    class Meta:
        ordering = ['title', 'author']

class BookInstance(models.Model):
    """ Model representing a specific copy of a book (i.e. that can be borrowed from the library). """
    id = models.UUIDField(
            primary_key=True,
            default=uuid.uuid4,
            help_text='Unique ID for this particular book across the whole library'
        )
    book = models.ForeignKey(
            'Book',
            on_delete=models.RESTRICT,
            null=True
        )
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.SET_NULL, null = True, blank = True)

    LOAN_STATUS = (
            ('m', 'Maintenance'),
            ('o', 'On loan'),
            ('a', 'Available'),
            ('r', 'Reserved'),
        )

    status = models.CharField(
                max_length=1,
                choices=LOAN_STATUS,
                blank=True,
                default='m',
                help_text='Book Availability',
        )

    class Meta:
        ordering = ['due_back', 'book', 'author']
        permissions = (('can_mark_returned', 'Set book as returned'),)

    def __str__(self):
        """ String for representing the Model object. """
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        """ Determine if the book is overdue based on due date and current date. """
        return bool(self.due_back and date.today() > self.due_back)

class Author(models.Model):
    """ Model representing an author. """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """ Returns the URL to access a particular author instance. """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """ String representing the model. """
        return f'{self.last_name}, {self.first_name}'

class Language(models.Model):
    name = models.CharField(
            max_length=200,
            unique=True,
            help_text="Enter the book's natural language (e.g Arabic, English, etc.)"
        )

    def __str__(self):
        """ String for representing the model object """
        return self.name

    def get_absolute_url(self):
        return reverse('laguage-detail', arg[str(self.id)])

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='language_name_case_insensitive_unique',
                violation_error_message='Language already exists (case insensitive match)'
            )
        ]

locallibrary/catalog/views.py
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def index(request):
    """ View function for home page of site. """

    # Generate counts of the some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_vists', 0)
    num_visits += 1
    request.session['num_visits'] = num_visits

    # The total number of books with a certain word
    num_book_match = Book.objects.filter(title__icontains='fiction').count()
    num_genre_match = Genre.objects.filter(name__icontains='fiction').count()

    context = {
            'num_books': num_books,
            'num_instances': num_instances,
            'num_instances_available': num_instances_available,
            'num_authors': num_authors,
            'num_book_match': num_book_match,
            'num_genre_match': num_genre_match,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = 3
    # context_object_name = 'book_list' # your own name for the list as a template variable
    # queryset = Book.objects.filter(title__icontains='war')[:5] # top 5 books containing the title war
    # template_name = 'books/my_arbitrary_template_name_list.html' # Specify your own template name/location

    # def get_queryset(self):
    #   return Book.objects.filter(title__icontains='war')[:5] 

    # When defining context data, it is important to follow the pattern below for best practices.
    # def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        # context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        # context['some_data'] = 'This is just some data'
        # return context

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """ Generic class-based view listing books on load to current user. """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (
                BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
        )

class LoanedBooksListView(LoginRequiredMixin, generic.ListView):
    """ Generic class-based view listing borrowed books to librarians. """
    model = BookInstance
    template_name='catalog/bookinstance_list_borrowed.html'
    paginate_by = 10
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return (
                BookInstance.objects.filter(status__exact='o').order_by('due_back')
        )

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author: {{ author.last_name }}, {{ author.first_name }}</h1>
  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
      <hr />
      <a href="{{ book.get_absolute_url }}">{{ book.title }} ({{ book.bookinstance_set.all.count }})</a>
      <p>{{ book.summary }}</p>
    {% endfor %}
  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
            <li>
                <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}</a> ({{ author.date_of_birth }} - {% if author.date_of_death%}{{author.date_of_dateh}}{% endif %})
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr />
      <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
            <li>
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }}) - {{bookinst.borrower}}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}